### ISSUE TITLE
hdiutil create failed: the operation timeout

### ISSUE THREAD

**Issue by aki2014** [ninxsoft/Mist#81] opened 2023-08-15 22:04 UTC
### :beetle: Description

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
1. When creating iso for 12.6.8 and resizing created Image, it fails.

### :white_check_mark: Expected Behaviour

Describe what should be happening (ie. the happy path).

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): 0.9
- macOS Version (`sw_vers`): 21G725
Intel [Mac]

I see the message "authorization error" and "operation timeout" in Japanese.

**Comment by aki2014** [comment] 2023-08-15 22:05
![mist_error20230816](https://github.com/ninxsoft/Mist/assets/5282177/76177972-7922-4422-aefd-c8cab3beb41b)

**Comment by branigan1871** [comment] 2023-08-17 12:38
I encountered the same error!

**Comment by ninxsoft** [comment] 2023-08-25 09:34
Unfortunately I am unable to reproduce this error when creating a **macOS Monterey 12.6.8** ISO:

![ISO](https://github.com/ninxsoft/Mist/assets/4812595/3eec6f03-e6b7-4def-a98c-642a4d64a49d)

Having said that, I have made some recent changes to the logic that shrinks the ISO: #82

I will be releasing this adjacent fix shortly - I request that you try reproducing this error with the next version of **Mist.app** 🙏

**Comment by ninxsoft** [comment] 2023-08-25 10:35
[Mist version 0.9.1](https://github.com/ninxsoft/Mist/releases/tag/v0.9.1) is now available - if you can please test with this version and report back 🙌

**Comment by aki2014** [comment] 2023-08-27 13:24
Thank you. I installed the latest and it worked without any error.

**Comment by ninxsoft** [comment] 2023-08-27 13:26
Amazing! 🙌 I will go ahead and close the issue 🥳

**Closed by ninxsoft** 2023-08-27 13:26 UTC
Labels: bug
