### ISSUE TITLE
Download above 100% and dont stop

### ISSUE THREAD

**Issue by fgonga** [ninxsoft/Mist#137] opened 2024-08-05 16:25 UTC
### :beetle: Description
Download above 100%
Describe clearly and concisely what is not working.
When I try to download Macos Sierra 10.12.6 the download says that hi installos is 5.01 but it downloads more than that about 10gb and the percentage is above 1005
### :clipboard: Steps to Reproduce

Create media install for MacOs Sierra 10.12.6

### :white_check_mark: Expected Behaviour

Describe what should be happening (ie. the happy path).

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): **Version 0.10 (0.10)**
- macOS Version (`sw_vers`): **21H1222**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **MacBook Pro (Retina, 13-inch, Early 2015)**
  - Chip : **Intel**

### :camera: Screenshots
<img width="308" alt="Captura de Tela 2024-08-05 às 17 21 09" src="https://github.com/user-attachments/assets/64acd46a-08b4-4f91-b01c-cfbc281f5d22">

**Comment by 5T33Z0** [comment] 2024-08-25 05:21
Same goes for Cataline. But it seems to only affect large files like `InstallESDDmg.pkg`:

![Bildschirmfoto 2024-08-25 um 07 17 00](https://github.com/user-attachments/assets/15453f60-78bc-4bb2-9de2-eb4a2c644cd0)

**Comment by ninxsoft** [comment] 2024-10-05 01:31
Closing as this is a duplicate of https://github.com/ninxsoft/Mist/issues/15

**Closed by ninxsoft** 2024-10-05 01:31 UTC
Labels: bug, duplicate
