### ISSUE TITLE
Issue with Mist Privileged Helper Tool Still Prompting “Not Installed” After Installation

### ISSUE THREAD

**Issue by zhaodi940422** [ninxsoft/Mist#91] opened 2023-09-13 10:54 UTC
Hello everyone, I want to share a problem I encountered while using the Mist application, hoping to help friends who are also troubled by this.

After installing the Mist application, I installed the Mist Privileged Helper Tool as prompted. However, when I tried to use features that require administrator privileges, the system still prompted me with “Privileged Helper Tool not installed!”. This left me very confused because I had clearly installed the Helper Tool as required.

I  tried the following solutions, but none of them worked:

Completely close the Mist application and then reopen it.
Reinstall the Mist Privileged Helper Tool.
Check system settings to ensure that the Mist application has sufficient permissions.
Despite trying all possible solutions, the problem still persists. This leaves me feeling very frustrated and helpless.

If anyone has encountered a similar problem and found a solution, I hope you can share it in the comments below. Your help would be greatly appreciated.
<img width="372" alt="SCR-20230913-sczy" src="https://github.com/ninxsoft/Mist/assets/57597086/f1fb3d66-a016-4922-9ab8-979466e8f45a">

**Comment by bhagatparwinder** [comment] 2023-10-05 00:57
Duplicate of https://github.com/ninxsoft/Mist/issues/69

**Comment by ninxsoft** [comment] 2023-10-29 03:01
Closing due to being a duplicate of #69, let's keep the conversation going there 👍

**Closed** 2023-10-29 09:42 UTC
Labels: bug
