### ISSUE TITLE
Download Shows More than 100% and Larger than Download Size

### ISSUE THREAD

**Issue by brianhm** [ninxsoft/Mist#92] opened 2023-09-13 13:41 UTC
Running latest version of MIST, running beta version of Ventura.  This has also happened to me on the beta version of Sonoma.  The CLI version seems to work properly when downloading.

<img width="477" alt="Screenshot 2023-09-13 at 9 37 36 AM" src="https://github.com/ninxsoft/Mist/assets/103964858/604652e5-ce7b-43ad-9444-8220f75978b6">

**Comment by RashMacAdmin** [comment] 2023-09-27 01:14
I can also confirm I have seen this issue across numerous release builds of Ventura. It occurred tonight running MacOS 13.5.2 (22G91) - M1 Max - Jamf Hybrid MDM

**Comment by ninxsoft** [comment] 2023-10-28 08:13
Closing this issue as it's a duplicate of #15

Let's keep the conversation going there 👍

**Closed by ninxsoft** 2023-10-28 08:13 UTC
Labels: bug, duplicate
