### ISSUE TITLE
Downloading firmware passed 100% after wake from sleep

### ISSUE THREAD

**Issue by marcelpogorzelski** [ninxsoft/Mist#124] opened 2024-03-08 11:14 UTC
### :beetle: Description

Downloading firmware jumped from about 50% to about 150% after my computer woke up from sleep. I had to abort download and start again as I didn't have the time to test.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
1. Click on download Firmware 14.4 button
1. Wait for computer to go to sleep
1. Wake computer up
1. Observe error

### :white_check_mark: Expected Behaviour

Continue download from where it left

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): **0.10**
- macOS Version (`sw_vers`): **23E214**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **MacBookPro18,2**
  - Chip : **Apple M1 Max**

### :camera: Screenshots
![image](https://github.com/ninxsoft/Mist/assets/42753253/1a65eb3e-8caf-430f-b9e2-263d98597fce)

**Comment by ninxsoft** [comment] 2024-04-17 08:40
@marcelpogorzelski thanks for reporting this! Looks like it's a duplicate of #15

Will keep the conversation going there 👍

**Closed** 2024-04-17 08:40 UTC
Labels: bug, duplicate
